#pragma once

#define FIRMWARE_VERSION_MAJOR 0
#define FIRMWARE_VERSION_MINOR 2
#define FIRMWARE_VERSION_PATCH 3

#define FIRMWARE_VERSION "0.2.4"
#define PRODUCT_NAME "4CH Power Meter"

// Framework compatibility macros
#define PROJECT_NAME PRODUCT_NAME
#define PROJECT_VERSION FIRMWARE_VERSION
